# .platform.app.yaml
name: app
type: python:3.9  # Your Python runtime version

dependencies:
  python3:
    pipenv: '2023.2.4'

web:
    commands:
        start: uvicorn main:app --host 0.0.0.0 --port 8080
    locations:
        "/":
            root: public
            allow: true

hooks:
    build: |
        pip install -r requirements.txt