# .platform.app.yaml
name: app
type: python:3.12 

dependencies:
  python3:
    pipenv: '2023.2.4'

web:
    commands:
        start: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    locations:
        "/":
            root: public
            allow: true

workers:
  count: 4

hooks:
    build: |
        pip install -r requirements.txt

disk: 512

mounts:
    "/static": "shared:files/static"