name: app
type: python:3.9

relationships:
  database: "db:mysql"
  rediscache: "cache:redis"

# .platform.app.yaml
dependencies:
    python:
        fastapi: "latest"
        uvicorn: "latest"
        mysqlclient: "latest"

build:
    flavor: fastcgi

web:
    commands:
        start: uvicorn main:app --host 0.0.0.0 --port 8080
    locations:
        "/":
            root: public
            allow: true

hooks:
    build: |
        pip install -r requirements.txt