name: app
type: python:3.9

relationships:
    database: "mysql:mysql"  # Ensure this targets the correct database endpoint

dependencies:
    python:
        - fastapi
        - uvicorn
        - mysqlclient  # MySQL client for Python

build:
    flavor: fastcgi

web:
    commands:
        start: uvicorn main:app --host 0.0.0.0 --port 8080
    locations:
        "/":
            root: public
            index: index.html
            allow: true

hooks:
    build: |
        pip install -r requirements.txt