name: app
type: "python:3.9"
web:
    commands:
        start: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    mounts:
        "/": "shared:files"
relationships:
    database: "mysql:mysql"
dependencies:
    python: "requirements.txt"